# Generated by Django 4.2.16 on 2025-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('vapers', 'Vapers'), ('liquidos', 'Líquidos'), ('pods', 'Pods')], default='vapers', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(default='https://www.iplayvape.com/uploads/IPLAY-WALKER-DISPOSABLE-VAPE-1.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
